name: Codenarc check

on:
  pull_request:
    branches: [master, main]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: gradle build CodenarcMain codenarcTest --info

      - name: Upload Codenarc Report
        uses: actions/upload-artifact@v2
        with:
          name: Codenarc Report 
          path: build/reports/codenarc

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create and switch to codenarc branch
        run: |
          echo "git branch"
          git branch
          echo "git branch"
          git status
          echo "git fetch origin"
          git fetch origin
          echo "git checkout -f codenarc"
          git checkout -f codenarc
          echo "cp -rf build/reports/codenarc/main.html docs/main.html"
          cp -rf build/reports/codenarc/main.html docs/main.html

      - name: Commit and push changes
        run: |
          echo "git branch"
          git branch
          echo "git status"
          git status
          echo "git add docs/"
          git add docs/
          echo "git commit -m Update Codenarc Report"
          git commit -m "Update Codenarc Report"
          echo "git push origin codenarc"
          git push origin codenarc   
