name: Codenarc check

on:
  pull_request:
    branches: [master, main]
    paths:
      - 'src'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: gradle CodenarcMain codenarcTest

      - name: Upload Codenarc Report
        if: ${{ failure() }} 
        uses: actions/upload-artifact@v2
        with:
          name: Codenarc Report 
          path: build/reports/codenarc

      - name: Configure Git
        if: ${{ failure() }} 
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create and switch to gh-pages branch
        if: ${{ failure() }} 
        run: |
          echo "git branch"
          git branch
          echo "git status"
          git status
          echo "git fetch origin"
          git fetch origin
          echo "git checkout -f gh-pages"
          git checkout -f gh-pages
          echo "cp build/reports/codenarc/main.html docs/main.html"
          cp build/reports/codenarc/main.html docs/codenarc.html

      - name: Commit and push changes
        if: ${{ failure() }} 
        run: |
          echo "git branch"
          git branch
          echo "git status"
          git status
          echo "git add docs/"
          git add docs/
          echo "git commit -m Update Codenarc Report"
          git commit -m "Update Codenarc Report"
          echo "git push origin gh-pages"
          git push origin gh-pages
          
      - name: Codenarc Report
        if: ${{ failure() }} 
        run: |
          echo "Link: [Codenarc Report](https://kinjen39.github.io/alt-jenkins-actions/codenarc.html)" >> $GITHUB_STEP_SUMMARY
          
      - name: Comment Report
        if: ${{ failure() }} 
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ⚠️ Link: [Codenarc Report](https://kinjen39.github.io/alt-jenkins-actions/codenarc.html)
