name: Flake8 Check

on:
  pull_request:
    paths:
      - '**/*.py' # Adjust the path pattern to match your project's Python files

jobs:
  flake8:
    name: Run Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Choose the desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Get PR Changed Files
        run: echo "::set-env name=CHANGED_FILES::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$')"

      - name: Run Flake8 on Changed Files
        run: |
          changed_files=${{ env.CHANGED_FILES }}
          if [ -n "$changed_files" ]; then
            echo "Running Flake8 on changed files:"
            echo "$changed_files"
            flake8 $changed_files
          else
            echo "No changed Python files found."
          fi
