name: flake8 Lint plugin

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
  
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38
        with:
          files_yaml: |
            python:
              - '**.py'
    
      - name: Exit workflow if no .py file has been added or modified
        run: |
          if [ "${{ steps.changed-files.outputs.python_all_changed_files_count }}" != 0 ]; then
            echo "execute_flake8=true" >> $GITHUB_ENV
          else
            echo "execute_flake8=false" >> $GITHUB_ENV
            echo "Exiting workflow: no .py file has been added or modified"
          fi


      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.python_all_changed_files }}; do
            echo "$file was changed"
          done
          echo ${{ env.execute_flake8 }}
          
      - name: Check out source repository
        uses: actions/checkout@v3
        if: env.execute_flake8 == "true"

      - name: Check variable
        run: |
          echo ${{ env.execute_flake8 }}

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
        if: env.execute_flake8 == 'true'

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "${{ steps.changed-files.outputs.python_all_changed_files }}"
          plugins: "flake8-unused-globals==0.1.10"
        if: env.execute_flake8 == "true"
