name: flake8 Lint

on:
  pull_request:
    branches: [master, main]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Flake8
        uses: ricardochaves/python-lint@v1.4.0
        with:
            python-root-list: ${{ steps.changed-files.outputs.all_changed_files }}
            use-pylint: false
            use-pycodestyle: false
            use-flake8: true
            use-black: false
            use-mypy: false
            use-isort: false
