# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    name: Test gradle image
    runs-on: ubuntu-latest

    container:
      image: rust:1.67

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    #- name: Check Clippy
    #  run: cargo clippy --version
    - name: Try running clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
